source 'http://rubygems.org'

gem 'byebug'
gem 'faraday'
gem 'logger'
gem 'pg'
gem 'puma'
gem 'rack'
gem 'rack-cors'
gem 'rack-flash3'
gem 'rackup'
gem 'sinatra'
gem 'webdrivers'

group :test do
  gem 'capybara'
  gem 'rack-test'
  gem 'rspec'
  gem 'selenium-webdriver'
end
