require 'pg'
require 'rake'

namespace :db do
  task :create_test do
    begin
      conn = PG.connect(
        host: 'postgres',
        user: 'user',
        password: 'pass',
        dbname: 'postgres' # Connect to the default 'postgres' database to create the target one
      )
      conn.exec("CREATE DATABASE test_rebaselabs;")
      conn.close
      puts "Database 'test_rebaselabs' created."
    rescue PG::DuplicateDatabase
      puts "Database 'test_rebaselabs' already exists, skipping creation."
    end
  end

  task :drop_test do
    begin
      conn = PG.connect(
        host: 'postgres',
        user: 'user',
        password: 'pass',
        dbname: 'postgres' # Connect to the default 'postgres' database to drop the target one
      )
      conn.exec("DROP DATABASE IF EXISTS test_rebaselabs;")
      conn.close
      puts "Database 'test_rebaselabs' dropped."
    rescue PG::UndefinedDatabase
      puts "Database 'test_rebaselabs' does not exist, skipping drop."
    end
  end
end

desc 'Run specs'
task spec: ['db:create_test'] do
  begin
    # Ensure the test database is used
    ENV['DATABASE_NAME'] = 'test_rebaselabs'

    # Your spec task implementation
    Rake::Task['spec:run'].invoke
  ensure
    # Drop the test database after running the tests
    Rake::Task['db:drop_test'].invoke
  end
end

namespace :spec do
  task :run do
    # Run your test suite here, e.g., using RSpec
    sh 'rspec'
  end
end